# Generated by Django 5.2 on 2025-04-14 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='接收日期')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='预留数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouse.location', verbose_name='位置')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(choices=[('cycle', '周期盘点'), ('full', '全面盘点'), ('sample', '抽样盘点')], default='cycle', max_length=20, verbose_name='盘点类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counts', to=settings.AUTH_USER_MODEL, verbose_name='分配给')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='warehouse.location', verbose_name='位置')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(verbose_name='预期数量')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, verbose_name='盘点数量')),
                ('is_discrepancy', models.BooleanField(default=False, verbose_name='是否有差异')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.inventory', verbose_name='库存')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='库存盘点')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '库存盘点项目',
                'verbose_name_plural': '库存盘点项目',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('increase', '增加'), ('decrease', '减少')], max_length=20, verbose_name='交易类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('previous_quantity', models.IntegerField(verbose_name='之前数量')),
                ('new_quantity', models.IntegerField(verbose_name='新数量')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='引用类型')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='引用ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.batch', verbose_name='批次')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventory', verbose_name='库存')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存交易记录',
                'verbose_name_plural': '库存交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='条形码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售价')),
                ('min_stock_level', models.IntegerField(default=0, verbose_name='最低库存水平')),
                ('reorder_point', models.IntegerField(default=0, verbose_name='再订购点')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长度(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽度(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高度(cm)')),
                ('handling_instructions', models.TextField(blank=True, null=True, verbose_name='处理说明')),
                ('storage_requirements', models.TextField(blank=True, null=True, verbose_name='存储要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', '低库存'), ('out_of_stock', '缺货'), ('expiring', '即将过期'), ('expired', '已过期')], max_length=20, verbose_name='警报类型')),
                ('status', models.CharField(choices=[('active', '激活'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='active', max_length=20, verbose_name='状态')),
                ('message', models.TextField(verbose_name='消息')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存警报',
                'verbose_name_plural': '库存警报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product', verbose_name='产品'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品属性',
                'verbose_name_plural': '产品属性',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='属性值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productattribute', verbose_name='属性')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='inventory.product', verbose_name='产品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品属性值',
                'verbose_name_plural': '产品属性值',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='父类别')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='类别'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='图片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='产品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='序列号')),
                ('status', models.CharField(choices=[('available', '可用'), ('reserved', '已预留'), ('sold', '已售出'), ('damaged', '已损坏'), ('returned', '已退回')], default='available', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.batch', verbose_name='批次')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='位置')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.product', verbose_name='产品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '序列号',
                'verbose_name_plural': '序列号',
            },
        ),
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='预留数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_inventory', to='inventory.batch', verbose_name='批次')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_inventory', to='inventory.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '批次库存',
                'verbose_name_plural': '批次库存',
                'unique_together': {('inventory', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['status'], name='inventory_i_status_64a2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['count_type'], name='inventory_i_count_t_38aa08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycountitem',
            unique_together={('inventory_count', 'inventory')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_9acac2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_i_transac_2eccee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['alert_type'], name='inventory_i_alert_t_366cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['status'], name='inventory_i_status_f325a8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'location'], name='inventory_i_product_152fea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='inventory_b_batch_n_6c5580_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['serial_number'], name='inventory_s_serial__e6e8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status'], name='inventory_s_status_4d8d9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serialnumber',
            unique_together={('product', 'serial_number')},
        ),
    ]
