# Generated by Django 5.2 on 2025-04-14 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('receiving', '收货'), ('putaway', '上架'), ('picking', '拣货'), ('packing', '打包'), ('shipping', '发货'), ('stocktake', '盘点'), ('transfer', '转移'), ('other', '其他')], max_length=50, verbose_name='任务类型')),
                ('reference_type', models.CharField(blank=True, max_length=100, verbose_name='引用类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='引用ID')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=50, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('assigned', '已分配'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=50, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='分配用户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'warehouse_task',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warehouse.task', verbose_name='任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
                'db_table': 'warehouse_task_history',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, verbose_name='仓库代码')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse_warehouse',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='warehouse.warehouse', verbose_name='仓库'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('code', models.CharField(max_length=50, verbose_name='区域代码')),
                ('description', models.TextField(blank=True, verbose_name='区域描述')),
                ('zone_type', models.CharField(max_length=50, verbose_name='区域类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'warehouse_zone',
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('code', models.CharField(max_length=50, verbose_name='位置代码')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='条形码')),
                ('location_type', models.CharField(max_length=50, verbose_name='位置类型')),
                ('aisle', models.CharField(blank=True, max_length=50, verbose_name='通道')),
                ('rack', models.CharField(blank=True, max_length=50, verbose_name='货架')),
                ('shelf', models.CharField(blank=True, max_length=50, verbose_name='层')),
                ('bin', models.CharField(blank=True, max_length=50, verbose_name='格')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大承重')),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大体积')),
                ('is_pickable', models.BooleanField(default=True, verbose_name='是否可拣货')),
                ('is_receivable', models.BooleanField(default=True, verbose_name='是否可收货')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehouse', verbose_name='仓库')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.zone', verbose_name='区域')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
                'db_table': 'warehouse_location',
                'unique_together': {('warehouse', 'code')},
            },
        ),
    ]
